openapi: 3.0.0

info:
  title: Podcasts API
  description: Add, find and filter your favorite podcasts
  version: 1.0.0
  contact: marcosvcorsi@gmail.com

paths:
  /podcasts:
    post:
      tags:
        - Podcasts
      summary: Create a Podcast
      description: Create a new Podcast.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                links:
                  type: array
                  items:
                    type: string   
      responses:
        200:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  links:
                    type: array
                    items:
                      type: string
        400:
          description: Podcast already exists                           